### ISSUE TITLE
Replay logger script

### ISSUE THREAD

**Issue by Eric-Wallace** [cole-maclean/autocraft#1]
I am interested in the work you put together. I am wondering if you could open source either the script used to create the dataset from the raw replays or the dataset itself.

**Comment by cole-maclean** [comment]
Customized replay_actions.py scrapper for collecting the data can be found [here](https://github.com/cole-maclean/pysc2/blob/state-scrapper/pysc2/bin/replay_actions.py)

**Comment by cole-maclean** [comment]
PR in place for pySC2 to allow for custom replay data parsers: https://github.com/deepmind/pysc2/pull/119
